---
Name: jellygnite-elementalstyle
After: jellygnite-elements
---
DNADesign\Elemental\Models\BaseElement:
  inline_editable: false
  extensions:
    - Jellygnite\ElementalStyle\Extensions\DynamicStyleExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - jellygnite/silverstripe-brandpad:client/dist/admin/css/bundle.css
  extra_requirements_javascript:
    - jellygnite/silverstripe-elemental-style:client/dist/javascript/bundle.js